version = 1

[corsa_upstream]
path = "ref/corsa-upstream"
repository = "https://github.com/microsoft/typescript-go.git"
commit = "2bd066d87f5bafd315be9f40889d0a60b9e58e0b"
tree = "ed2c2c12c401b84bd5888d0b889737495aa93a20"
committer_date = "2026-07-07T21:22:40-07:00"
author = "Jake Bailey"
subject = "Merge branch 'main' into ts7-release"
