version = 1

[corsa_upstream]
path = "ref/corsa-upstream"
repository = "https://github.com/microsoft/TypeScript.git"
commit = "d61a7d235906e78be9b111de0ba060e28e67ecfa"
tree = "07ca7fcb1496db76af26dcd919f66e8e222ad95d"
committer_date = "2026-10-06T23:09:58Z"
author = "Christopher Plieger"
subject = "[api] Skip disk-layout import diagnostics for customized module resolutions (#64638)"
