version = 1

[typescript_go]
path = "ref/typescript-go"
repository = "https://github.com/microsoft/typescript-go.git"
commit = "f4a1d2a1d0d5df4333f2440500e3a6c4b4702d9a"
tree = "db15a071b5981d71e41c086859133cb15ef67cb3"
committer_date = "2026-05-15T23:24:59Z"
author = "navya9singh"
subject = "Adding signature help tooltip coloring support for VS (#3821)"
