//! Committed golden conformance corpus for the native stylistic rules.
//!
//! `stylistic_golden.json` is generated by `.cache/oracle/build_golden.mjs`,
//! which runs each snippet through the REAL `@stylistic` plugin and records the
//! true violation count under the given options. Unlike
//! [`super::stylistic_conformance`], the corpus is committed and embedded with
//! `include_str!`, so it runs in CI without the oracle install and exercises
//! option paths as well as defaults.
//!
//! Regenerate after changing rule behaviour:
//! `cd .cache/oracle && node build_golden.mjs`.

#![cfg(test)]

use serde::Deserialize;
use serde_json::Value;

use super::{run_stylistic_lint, StylisticRuleConfig, StylisticRunConfig};

const GOLDEN: &str = include_str!("stylistic_golden.json");

#[derive(Deserialize)]
struct GoldenCase {
    rule: String,
    code: String,
    #[serde(default)]
    options: Option<Value>,
    errors: u64,
}

#[test]
fn stylistic_rules_match_committed_golden_corpus() {
    let cases: Vec<GoldenCase> =
        serde_json::from_str(GOLDEN).expect("stylistic_golden.json must be valid JSON");
    assert!(!cases.is_empty(), "golden corpus must not be empty");

    let mut failures = Vec::new();
    for case in &cases {
        let options = case.options.clone().unwrap_or(Value::Null);
        let config = StylisticRunConfig {
            rules: vec![StylisticRuleConfig {
                name: case.rule.clone(),
                options,
            }],
        };
        let actual = match run_stylistic_lint(&case.code, &config) {
            Ok(diagnostics) => diagnostics
                .iter()
                .filter(|diagnostic| diagnostic.rule_name == case.rule)
                .count() as u64,
            Err(err) => {
                failures.push(format!("{}: run error {err} for {:?}", case.rule, case.code));
                continue;
            }
        };
        if actual != case.errors {
            failures.push(format!(
                "{}: expected {} got {} for {:?}{}",
                case.rule,
                case.errors,
                actual,
                case.code,
                case.options
                    .as_ref()
                    .map(|o| format!(" options={o}"))
                    .unwrap_or_default()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} golden cases diverged from @stylistic:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}
