/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Thin synchronous wrapper around the Rust stdio API client. */
export declare class CorsaApiClient {
  /** Spawns a new client from a JavaScript spawn config. */
  static spawn(options: any): CorsaApiClient
  /** Spawns a new client without blocking the JavaScript event loop. */
  static spawnAsync(options: any): Promise<CorsaApiClient>
  /** Calls `initialize` and returns the response object. */
  initialize(): any
  /** Calls `initialize` without blocking the JavaScript event loop. */
  initializeAsync(): Promise<unknown>
  /** Parses a `tsconfig` through corsa and returns the response object. */
  parseConfigFile(file: string): any
  /** Parses a `tsconfig` on a libuv worker thread. */
  parseConfigFileAsync(file: string): Promise<unknown>
  /** Applies file changes and returns a snapshot record. */
  updateSnapshot(params?: any | undefined | null): any
  /** Applies file changes on a libuv worker thread. */
  updateSnapshotAsync(params?: any | undefined | null): Promise<unknown>
  /** Fetches a source file through the binary endpoint. */
  getSourceFile(snapshot: string, project: string, file: string): Uint8Array | null
  /** Fetches a source file on a libuv worker thread. */
  getSourceFileAsync(snapshot: string, project: string, file: string): Promise<Uint8Array | null>
  /** Resolves the intrinsic string type for a project. */
  getStringType(snapshot: string, project: string): any
  getStringTypeAsync(snapshot: string, project: string): Promise<unknown>
  /** Resolves the checker type visible at a file position. */
  getTypeAtPosition(snapshot: string, project: string, file: string, position: number): any
  getTypeAtPositionAsync(snapshot: string, project: string, file: string, position: number): Promise<unknown>
  /** Resolves the checker type for a source range using Rust-side lookup hints. */
  getTypeAtSourceRange(snapshot: string, project: string, file: string, start: number, end: number, sourceText: string, kind?: string | undefined | null): any
  getTypeAtSourceRangeAsync(snapshot: string, project: string, file: string, start: number, end: number, sourceText: string, kind?: string | undefined | null): Promise<unknown>
  /** Resolves the checker symbol visible at a file position. */
  getSymbolAtPosition(snapshot: string, project: string, file: string, position: number): any
  getSymbolAtPositionAsync(snapshot: string, project: string, file: string, position: number): Promise<unknown>
  /** Resolves checker symbols for source positions in one project-scoped request. */
  getSymbolsAtPositions(snapshot: string, project: string, file: string, positions: Array<number>): any
  getSymbolsAtPositionsAsync(snapshot: string, project: string, file: string, positions: Array<number>): Promise<unknown>
  /** Follows all aliases for a checker symbol in its owning project. */
  getAliasedSymbol(snapshot: string, project: string, symbol: string): any
  getAliasedSymbolAsync(snapshot: string, project: string, symbol: string): Promise<unknown>
  /** Follows one alias edge for a checker symbol in its owning project. */
  getImmediateAliasedSymbol(snapshot: string, project: string, symbol: string): any
  getImmediateAliasedSymbolAsync(snapshot: string, project: string, symbol: string): Promise<unknown>
  /** Returns the checker-owned exports of a module symbol. */
  getExportsOfModule(snapshot: string, project: string, symbol: string): any
  getExportsOfModuleAsync(snapshot: string, project: string, symbol: string): Promise<unknown>
  /**
   * Resolves the symbol attached to a checker type.
   *
   * Passing the owning project keeps the lookup working on TypeScript 7
   * stable runtimes, which resolve type symbols inside a project.
   */
  getSymbolOfType(snapshot: string, typeHandle: string, project?: string | undefined | null): any
  getSymbolOfTypeAsync(snapshot: string, typeHandle: string, project?: string | undefined | null): Promise<unknown>
  /** Resolves type arguments for type-reference and mapped objects, and returns [] otherwise. */
  getTypeArguments(snapshot: string, project: string, typeHandle: string, objectFlags?: number | undefined | null): any
  /** Resolves type arguments and prefers structural handles from source locations when available. */
  getTypeArgumentsAtSourceRange(snapshot: string, project: string, typeHandle: string, objectFlags: number | undefined | null, file: string, start: number, end: number, sourceText: string): any
  getTypeArgumentsAsync(snapshot: string, project: string, typeHandle: string, objectFlags?: number | undefined | null): Promise<unknown>
  getTypeArgumentsAtSourceRangeAsync(snapshot: string, project: string, typeHandle: string, objectFlags: number | undefined | null, file: string, start: number, end: number, sourceText: string): Promise<unknown>
  /** Resolves a named property on a checker type in its owning project. */
  getPropertyOfType(snapshot: string, project: string, typeHandle: string, name: string): any
  getPropertyOfTypeAsync(snapshot: string, project: string, typeHandle: string, name: string): Promise<unknown>
  /** Returns whether `source` is assignable to `target` in the owning project. */
  isTypeAssignableTo(snapshot: string, project: string, source: string, target: string): any
  isTypeAssignableToAsync(snapshot: string, project: string, source: string, target: string): Promise<unknown>
  /** Resolves a type constraint using Corsa relation endpoints. */
  getConstraintOfType(snapshot: string, project: string, typeHandle: string): any
  getConstraintOfTypeAsync(snapshot: string, project: string, typeHandle: string): Promise<unknown>
  /** Resolves the apparent checker type of a symbol. */
  getTypeOfSymbol(snapshot: string, project: string, symbol: string): any
  getTypeOfSymbolAsync(snapshot: string, project: string, symbol: string): Promise<unknown>
  /** Resolves the declared checker type of a symbol. */
  getDeclaredTypeOfSymbol(snapshot: string, project: string, symbol: string): any
  getDeclaredTypeOfSymbolAsync(snapshot: string, project: string, symbol: string): Promise<unknown>
  /** Renders a type back to a string representation. */
  typeToString(snapshot: string, project: string, typeHandle: string, location?: string | undefined | null, flags?: number | undefined | null): string
  typeToStringAsync(snapshot: string, project: string, typeHandle: string, location?: string | undefined | null, flags?: number | undefined | null): Promise<unknown>
  /** Sends an arbitrary JSON endpoint request. */
  callJson(method: string, params?: any | undefined | null): any
  /** Sends an arbitrary JSON endpoint request on a libuv worker thread. */
  callJsonAsync(method: string, params?: any | undefined | null): Promise<unknown>
  /** Sends an arbitrary binary endpoint request. */
  callBinary(method: string, params?: any | undefined | null): Uint8Array | null
  /** Sends an arbitrary binary endpoint request on a libuv worker thread. */
  callBinaryAsync(method: string, params?: any | undefined | null): Promise<Uint8Array | null>
  /** Releases a corsa handle explicitly. */
  releaseHandle(handle: string): void
  /** Releases a corsa handle on a libuv worker thread. */
  releaseHandleAsync(handle: string): Promise<void>
  /** Closes the underlying worker process. */
  close(): void
  /** Closes the underlying worker process on a libuv worker thread. */
  closeAsync(): Promise<void>
}

/** N-API wrapper for the distributed orchestration layer. */
export declare class CorsaDistributedOrchestrator {
  /** Creates a new in-process Raft cluster. */
  constructor(nodeIds: Array<string>)
  /** Starts a leader election and returns the resulting term. */
  campaign(nodeId: string): number
  /** Returns the current leader identifier. */
  leaderId(): string | null
  /** Returns the leader state. */
  state(): any | null
  /** Returns the state for a single node. */
  nodeState(nodeId: string): any | null
  /** Returns a replicated document if it exists. */
  document(nodeId: string, uri: string): any | null
  /** Replicates an opened document and returns the state. */
  openVirtualDocument(document: any): any
  /** Applies replicated incremental changes and returns the state. */
  changeVirtualDocument(uri: string, changes: any): any
  /** Removes a replicated document. */
  closeVirtualDocument(uri: string): void
}

/** Mutable virtual document mirrored through the LSP overlay layer. */
export declare class CorsaVirtualDocument {
  /** Creates an `untitled:` document. */
  static untitled(path: string, languageId: string, text: string): CorsaVirtualDocument
  /** Creates an in-memory `corsa://` document. */
  static inMemory(authority: string, path: string, languageId: string, text: string): CorsaVirtualDocument
  /** Returns the document URI. */
  get uri(): string
  /** Returns the language identifier. */
  get languageId(): string
  /** Returns the current version number. */
  get version(): number
  /** Returns the current full text. */
  get text(): string
  /** Returns the full document state. */
  state(): any
  /** Replaces the entire document text. */
  replace(text: string): void
  /** Applies a batch of LSP changes. */
  applyChanges(changes: any): any
}

export declare function classifyTypeText(text?: string | undefined | null): string

export declare function isAnyLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isArrayLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isBigIntLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isErrorLikeTypeTexts(typeTexts: Array<string>, propertyNames?: Array<string> | undefined | null): boolean

export declare function isNumberLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isPromiseLikeTypeTexts(typeTexts: Array<string>, propertyNames?: Array<string> | undefined | null): boolean

export declare function isStringArrayLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isStringLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isUnknownLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isUnsafeAssignment(input: any): boolean

export declare function isUnsafeReturn(input: any): boolean

export declare function nativeLintRuleMetas(): any

export declare function runNativeLintRule(ruleName: string, node: any): any

/** Spawns a new client on a libuv worker thread. */
export declare function spawnCorsaApiClientAsync(options: any): Promise<CorsaApiClient>

export declare function splitTopLevelTypeText(text: string, delimiter: string): Array<string>

export declare function splitTypeText(text: string): Array<string>

/**
 * Returns the package version exposed by the native addon.
 *
 * # Examples
 *
 * ```
 * assert_eq!(corsa_node::version(), env!("CARGO_PKG_VERSION"));
 * ```
 */
export declare function version(): string
