/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Thin synchronous wrapper around the Rust stdio API client. */
export declare class TsgoApiClient {
  /** Spawns a new client from a JSON-encoded spawn config. */
  static spawn(optionsJson: string): TsgoApiClient
  /** Calls `initialize` and returns the raw JSON response. */
  initializeJson(): string
  /** Calls `initialize` without blocking the JavaScript event loop. */
  initializeJsonAsync(): Promise<string>
  /** Parses a `tsconfig` through tsgo and returns the JSON response. */
  parseConfigFileJson(file: string): string
  /** Parses a `tsconfig` on a libuv worker thread. */
  parseConfigFileJsonAsync(file: string): Promise<string>
  /** Applies file changes and returns a serialized snapshot record. */
  updateSnapshotJson(paramsJson?: string | undefined | null): string
  /** Applies file changes on a libuv worker thread. */
  updateSnapshotJsonAsync(paramsJson?: string | undefined | null): Promise<string>
  /** Fetches a source file through the binary endpoint. */
  getSourceFile(snapshot: string, project: string, file: string): Buffer | null
  /** Fetches a source file on a libuv worker thread. */
  getSourceFileAsync(snapshot: string, project: string, file: string): Promise<Buffer | null>
  /** Resolves the intrinsic string type for a project. */
  getStringTypeJson(snapshot: string, project: string): string
  getStringTypeJsonAsync(snapshot: string, project: string): Promise<string>
  /** Resolves the checker type visible at a file position. */
  getTypeAtPositionJson(snapshot: string, project: string, file: string, position: number): string
  getTypeAtPositionJsonAsync(snapshot: string, project: string, file: string, position: number): Promise<string>
  /** Resolves the checker symbol visible at a file position. */
  getSymbolAtPositionJson(snapshot: string, project: string, file: string, position: number): string
  getSymbolAtPositionJsonAsync(snapshot: string, project: string, file: string, position: number): Promise<string>
  /** Resolves type arguments for type-reference objects and returns [] otherwise. */
  getTypeArgumentsJson(snapshot: string, project: string, typeHandle: string, objectFlags?: number | undefined | null): string
  getTypeArgumentsJsonAsync(snapshot: string, project: string, typeHandle: string, objectFlags?: number | undefined | null): Promise<string>
  /** Resolves the apparent checker type of a symbol. */
  getTypeOfSymbolJson(snapshot: string, project: string, symbol: string): string
  getTypeOfSymbolJsonAsync(snapshot: string, project: string, symbol: string): Promise<string>
  /** Resolves the declared checker type of a symbol. */
  getDeclaredTypeOfSymbolJson(snapshot: string, project: string, symbol: string): string
  getDeclaredTypeOfSymbolJsonAsync(snapshot: string, project: string, symbol: string): Promise<string>
  /** Renders a type back to a string representation. */
  typeToString(snapshot: string, project: string, typeHandle: string, location?: string | undefined | null, flags?: number | undefined | null): string
  typeToStringAsync(snapshot: string, project: string, typeHandle: string, location?: string | undefined | null, flags?: number | undefined | null): Promise<string>
  /** Sends an arbitrary JSON endpoint request. */
  callJson(method: string, paramsJson?: string | undefined | null): string
  /** Sends an arbitrary JSON endpoint request on a libuv worker thread. */
  callJsonAsync(method: string, paramsJson?: string | undefined | null): Promise<string>
  /** Sends an arbitrary binary endpoint request. */
  callBinary(method: string, paramsJson?: string | undefined | null): Buffer | null
  /** Sends an arbitrary binary endpoint request on a libuv worker thread. */
  callBinaryAsync(method: string, paramsJson?: string | undefined | null): Promise<Buffer | null>
  /** Releases a tsgo handle explicitly. */
  releaseHandle(handle: string): void
  /** Releases a tsgo handle on a libuv worker thread. */
  releaseHandleAsync(handle: string): Promise<void>
  /** Closes the underlying worker process. */
  close(): void
  /** Closes the underlying worker process on a libuv worker thread. */
  closeAsync(): Promise<void>
}

/** N-API wrapper for the distributed orchestration layer. */
export declare class TsgoDistributedOrchestrator {
  /** Creates a new in-process Raft cluster. */
  constructor(nodeIds: Array<string>)
  /** Starts a leader election and returns the resulting term. */
  campaign(nodeId: string): number
  /** Returns the current leader identifier. */
  leaderId(): string | null
  /** Serializes the leader state. */
  stateJson(): string | null
  /** Serializes the state for a single node. */
  nodeStateJson(nodeId: string): string | null
  /** Serializes a replicated document if it exists. */
  documentJson(nodeId: string, uri: string): string | null
  /** Replicates an opened document and returns the serialized state. */
  openVirtualDocumentJson(leaderId: string, documentJson: string): string
  /** Applies replicated incremental changes and returns the serialized state. */
  changeVirtualDocumentJson(leaderId: string, uri: string, changesJson: string): string
  /** Removes a replicated document. */
  closeVirtualDocument(leaderId: string, uri: string): void
}

/** Mutable virtual document mirrored through the LSP overlay layer. */
export declare class TsgoVirtualDocument {
  /** Creates an `untitled:` document. */
  static untitled(path: string, languageId: string, text: string): TsgoVirtualDocument
  /** Creates an in-memory `corsa://` document. */
  static inMemory(authority: string, path: string, languageId: string, text: string): TsgoVirtualDocument
  /** Returns the document URI. */
  get uri(): string
  /** Returns the language identifier. */
  get languageId(): string
  /** Returns the current version number. */
  get version(): number
  /** Returns the current full text. */
  get text(): string
  /** Serializes the full document state. */
  stateJson(): string
  /** Replaces the entire document text. */
  replace(text: string): void
  /** Applies a batch of JSON-encoded LSP changes. */
  applyChangesJson(changesJson: string): string
}

export declare function classifyTypeText(text?: string | undefined | null): string

export declare function isAnyLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isArrayLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isBigIntLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isErrorLikeTypeTexts(typeTexts: Array<string>, propertyNames?: Array<string> | undefined | null): boolean

export declare function isNumberLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isPromiseLikeTypeTexts(typeTexts: Array<string>, propertyNames?: Array<string> | undefined | null): boolean

export declare function isStringArrayLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isStringLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isUnknownLikeTypeTexts(typeTexts: Array<string>): boolean

export declare function isUnsafeAssignment(inputJson: string): boolean

export declare function isUnsafeReturn(inputJson: string): boolean

export declare function nativeLintRuleMetasJson(): string

export declare function runNativeLintRule(ruleName: string, nodeJson: string): string

/** Spawns a new client on a libuv worker thread. */
export declare function spawnTsgoApiClientAsync(optionsJson: string): Promise<TsgoApiClient>

export declare function splitTopLevelTypeText(text: string, delimiter: string): Array<string>

export declare function splitTypeText(text: string): Array<string>

/**
 * Returns the package version exposed by the native addon.
 *
 * # Examples
 *
 * ```
 * assert_eq!(corsa_node::version(), env!("CARGO_PKG_VERSION"));
 * ```
 */
export declare function version(): string
